### ISSUE TITLE
Exception on wallet launch and CLI is crashing on empty password

### ISSUE THREAD

**Issue by honeycrypto** [semuxproject/semux-core#125]
v.1.5.0-RC2, latest commit of WIP PR
macOS 10.14.2

1) Existing wallet.data, both CLI and GUI log this to the console as soon as I launch wallet without trying to submit any password yet: 
```
./semux-cli.sh --network=testnet
ERROR    Wallet           org.bouncycastle.crypto.InvalidCipherTextException: pad block corrupted
```

2) Another test. Either due to some bug or accidentally I also created wallet with an empty password. 
CLI is crashing if password is empty, GUI seems to be working.
```
./semux-cli.sh --network=testnet
Exception in thread "main" java.lang.IllegalArgumentException: Password can not be null
	at org.semux.core.Wallet.unlock(Wallet.java:120)
	at org.semux.cli.SemuxCli.loadAndUnlockWallet(SemuxCli.java:334)
	at org.semux.cli.SemuxCli.start(SemuxCli.java:158)
	at org.semux.cli.SemuxCli.start(SemuxCli.java:142)
	at org.semux.cli.SemuxCli.main(SemuxCli.java:60)
	at org.semux.Main.main(Main.java:36)
```

**Comment by orogvany** [comment]
Err. Well #2 is a bug. Easy fix

**Comment by orogvany** [comment]
I can suppress the logging on #1 if you'd prefer

**Comment by orogvany** [comment]
fixed in RC2 branch
