### ISSUE TITLE
Error:  Corruption: not an sstable (bad magic number)

### ISSUE THREAD

**Issue by spaceblockstoken** [semuxproject/semux-core#16]
Semux/v1.2.0-cba85a7/Windows/amd64
OS: name = Microsoft Windows 10 build 17134
Java: version = 10.0.1, xmx = 10830 MB

```
2018-06-23T12:26:03-0700 INFO     SemuxSync        Syncing started, best known block = 427568
2018-06-23T12:26:04-0700 ERROR    SemuxGui         Uncaught exception during kernel startup.
org.iq80.leveldb.DBException: Corruption: not an sstable (bad magic number)
	at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:90) ~[semux.exe:cba85a7]
	at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:77) ~[semux.exe:cba85a7]
	at org.semux.db.LeveldbDatabase.get(LeveldbDatabase.java:119) ~[semux.exe:cba85a7]
	at org.semux.core.BlockchainImpl.getTransaction(BlockchainImpl.java:288) ~[semux.exe:cba85a7]
	at org.semux.core.BlockchainImpl.getTransactions(BlockchainImpl.java:469) ~[semux.exe:cba85a7]
	at org.semux.gui.SemuxGui.updateModel(SemuxGui.java:462) ~[semux.exe:cba85a7]
	at org.semux.gui.SemuxGui.startKernelAndMain(SemuxGui.java:331) ~[semux.exe:cba85a7]
	at org.semux.gui.SemuxGui.setupCoinbase(SemuxGui.java:299) [semux.exe:cba85a7]
	at org.semux.gui.SemuxGui.start(SemuxGui.java:191) [semux.exe:cba85a7]
	at org.semux.gui.SemuxGui.main(SemuxGui.java:103) [semux.exe:cba85a7]
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: not an sstable (bad magic number)
	at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:316) ~[semux.exe:cba85a7]
	at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:300) ~[semux.exe:cba85a7]
	at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:293) ~[semux.exe:cba85a7]
	at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:85) ~[semux.exe:cba85a7]
	... 9 more
2018-06-23T12:26:04-0700 INFO     Launcher         Shutting down pubsub-default
2018-06-23T12:26:04-0700 INFO     PubSub           PubSub service stopped
```

**Comment by semuxgo** [comment]
This is due to database corruption, typically when the client is not properly shut down.
