### ISSUE TITLE
VM: call failed on testnet

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#212]
As reported by @witoldsz

Contract:
```
pragma solidity ^0.5.7;

contract SimpleStorage {
    uint storedData;
    function set(uint x) public {
        storedData = x;
    }
    function get() public view returns (uint retVal) {
        return storedData;
    }
}
```

call:
```
0x60fe47b10000000000000000000000000000000000000000000000000000000000000009
```

Transaction: https://testnet.semux.info/explorer/account/0x5b0f9547fe2c5bac93f4e85ba293fdc397a1c38e

**Comment by semuxgo** [comment]
```
15:07:36.388 WARN     TransactionExecutor Exception occurred
org.ethereum.vm.program.exception.IllegalOperationException: Invalid operation code: opCode[1c];
	at org.ethereum.vm.program.exception.ExceptionFactory.invalidOpCode(ExceptionFactory.java:45) ~[evm-de88e39aa01be079c555f268953725076b151d85.jar:?]
	at org.ethereum.vm.VM.step(VM.java:137) ~[evm-de88e39aa01be079c555f268953725076b151d85.jar:?]
	at org.ethereum.vm.VM.play(VM.java:1120) ~[evm-de88e39aa01be079c555f268953725076b151d85.jar:?]
	at org.ethereum.vm.client.TransactionExecutor.execute(TransactionExecutor.java:257) [evm-de88e39aa01be079c555f268953725076b151d85.jar:?]
	at org.ethereum.vm.client.TransactionExecutor.run(TransactionExecutor.java:321) [evm-de88e39aa01be079c555f268953725076b151d85.jar:?]
	at org.semux.core.TransactionExecutor.executeVmTransaction(TransactionExecutor.java:280) [classes/:?]
	at org.semux.core.TransactionExecutor.execute(TransactionExecutor.java:237) [classes/:?]
	at org.semux.core.TransactionExecutor.execute(TransactionExecutor.java:321) [classes/:?]
	at org.semux.vm.client.VmTransactionTest.testCreateAndCall(VmTransactionTest.java:234) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.12.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.12.jar:4.12]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:?]
```
