### ISSUE TITLE
getTransactionResult fails for multiple tx's from same from in same block

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#215]
repro

vote/transfer/ or call in one block
call getTransactionResult
works

vote/transfer/call twice in one block
call getTransactionResult
fails

```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: input [274, 133], require: [274 275]
	at org.semux.util.SimpleDecoder.require(SimpleDecoder.java:131)
	at org.semux.util.SimpleDecoder.readSize(SimpleDecoder.java:112)
	at org.semux.util.SimpleDecoder.readBytes(SimpleDecoder.java:78)
	at org.semux.util.SimpleDecoder.readBytes(SimpleDecoder.java:89)
	at org.semux.core.BlockchainImpl.getTransactionResult(BlockchainImpl.java:302)
	at org.semux.gui.panel.TransactionsPanel$1.mousePressed(TransactionsPanel.java:92)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

note: might not require multiple tx's from same address.. might just fail on multiple tx's in block period.  not sure.

**Comment by orogvany** [comment]
Looks like fix for #221 resolves this
