### ISSUE TITLE
Error during /call

### ISSUE THREAD

**Issue by dinc334** [semuxproject/semux-core#257]
# 🐛 Bug

I create a simple contract with set/get funcs and public variable in testnet.
Contract address - 0x68badaa4b93cc043977a7c8647a05774df84d069
## To reproduce

1. open testnet api page
2. call 0x68badaa4b93cc043977a7c8647a05774df84d069 with 0xf8a8fd6d data

## Expected Behavior

 you will get a error in console
14:08:54.893 WARN     ApiHandlerImpl   Internal error
java.lang.reflect.InvocationTargetException: null
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at io.netty.channel.CombinedChannelDuplexHandler$

## System information

- Operating system: linux
- Semux version: 2.0.2

**Comment by semuxgo** [comment]
The temporary workaround is to fill the `from` address. We will fix this issue in next release.

**Comment by semuxgo** [comment]
Fixed as in v2.1
