### ISSUE TITLE
AtkWrapper not found

### ISSUE THREAD

**Issue by phash** [semuxproject/semux-core#64]
Hi there,

#### System information

Semux version: `1.4.0` (github clone)

OS & Version: Linux Mint 19

#### Expected behaviour
Gui starts

#### Actual behaviour
GUI does not start. Error message:
`Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at java.desktop/java.awt.Window.getToolkit(Window.java:1375)
	at java.desktop/java.awt.Window.init(Window.java:518)
	at java.desktop/java.awt.Window.<init>(Window.java:549)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/java.awt.Frame.<init>(Frame.java:388)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
	at org.semux.gui.WelcomeFrame.<init>(WelcomeFrame.java:59)
	at org.semux.gui.SemuxGui.showWelcome(SemuxGui.java:225)
	at org.semux.gui.SemuxGui.start(SemuxGui.java:192)
	at org.semux.gui.SemuxGui.main(SemuxGui.java:110)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
`
#### Steps to reproduce the behaviour

Try to run it on newer Ubuntu distributions with JDK10

stated as a bug here: https://bugs.openjdk.java.net/browse/JDK-8204862

**Comment by phash** [comment]
possible fix, but this has to be delivered from semux:
edit /etc/java-11-openjdk/accessibility.properties
comment the line
assistive_technologies=org.GNOME.Accessibility.AtkWrapper

this is not a good thing, though, we need a better solution

**Comment by semuxgo** [comment]
This is more of a JDK issue.
